# Generated by Django 4.1.6 on 2023-02-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.CharField(max_length=500, primary_key=True, serialize=False)),
                ('app_type', models.CharField(choices=[('свалка', 'свалка'), ('крупногабаритные отходы', 'крупногабаритные отходы'), ('переполненные контейнеры', 'переполненные контейнеры'), ('переполненные урны', 'переполненные урны')], max_length=255)),
                ('app_status', models.CharField(choices=[('ожидание', 'ожидание'), ('проверка', 'проверка'), ('реализация', 'реализация'), ('выполнен', 'выполнен')], max_length=255)),
                ('message', models.TextField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('patronymic', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=255)),
                ('photo_url', models.CharField(max_length=500)),
                ('video_url', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=600)),
                ('longitude', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=300)),
                ('user_id', models.CharField(max_length=400)),
                ('created_date', models.CharField(max_length=400)),
            ],
        ),
    ]
