# Generated by Django 4.1.6 on 2023-02-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0003_event_news"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="address",
            field=models.CharField(default="", max_length=600),
        ),
        migrations.AlterField(
            model_name="application",
            name="app_status",
            field=models.CharField(
                choices=[
                    ("ожидание", "ожидание"),
                    ("проверка", "проверка"),
                    ("реализация", "реализация"),
                    ("выполнен", "выполнен"),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="app_type",
            field=models.CharField(
                choices=[
                    ("свалка", "свалка"),
                    ("крупногабаритные отходы", "крупногабаритные отходы"),
                    ("переполненные контейнеры", "переполненные контейнеры"),
                    ("переполненные урны", "переполненные урны"),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="created_date",
            field=models.CharField(default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="application",
            name="first_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="application",
            name="last_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="application",
            name="latitude",
            field=models.CharField(default="", max_length=300),
        ),
        migrations.AlterField(
            model_name="application",
            name="longitude",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="application",
            name="patronymic",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="application",
            name="phone_number",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="application",
            name="photo_url",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="application",
            name="user_id",
            field=models.CharField(default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="application",
            name="video_url",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="event",
            name="address",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="event",
            name="created_date",
            field=models.CharField(default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.CharField(default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="event",
            name="document_url",
            field=models.CharField(default="", max_length=600),
        ),
        migrations.AlterField(
            model_name="event",
            name="latitude",
            field=models.DecimalField(decimal_places=6, default="", max_digits=100),
        ),
        migrations.AlterField(
            model_name="event",
            name="longitude",
            field=models.DecimalField(decimal_places=6, default="", max_digits=100),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizer_info",
            field=models.CharField(default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="event",
            name="time",
            field=models.CharField(default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="event",
            name="user_id",
            field=models.CharField(default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="news",
            name="author_id",
            field=models.CharField(default="", max_length=600),
        ),
        migrations.AlterField(
            model_name="news",
            name="created_date",
            field=models.CharField(default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="news",
            name="photo_url",
            field=models.CharField(default="", max_length=600),
        ),
        migrations.AlterField(
            model_name="news",
            name="small_description",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(default="", max_length=500),
        ),
    ]
