# Generated by Django 4.1.6 on 2023-02-09 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0006_alter_application_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="latitude",
            field=models.DecimalField(decimal_places=8, default=None, max_digits=100),
        ),
        migrations.AlterField(
            model_name="application",
            name="longitude",
            field=models.DecimalField(decimal_places=8, default=None, max_digits=100),
        ),
    ]
