# Generated by Django 4.1.6 on 2023-02-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0007_alter_application_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="latitude",
            field=models.CharField(blank=True, default="", max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="longitude",
            field=models.CharField(blank=True, default="", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="latitude",
            field=models.DecimalField(decimal_places=6, default="", max_digits=100),
        ),
        migrations.AlterField(
            model_name="event",
            name="longitude",
            field=models.DecimalField(decimal_places=6, default="", max_digits=100),
        ),
    ]
