# Generated by Django 4.1.6 on 2023-02-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0009_alter_application_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="created_date",
            field=models.DateField(default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(default="", max_length=400),
        ),
    ]
