# Generated by Django 4.1.6 on 2023-02-09 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0010_alter_event_created_date_alter_event_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="address",
            field=models.CharField(default="", max_length=600),
        ),
        migrations.AlterField(
            model_name="application",
            name="app_type",
            field=models.CharField(
                choices=[
                    ("свалка", "свалка"),
                    ("крупногабаритные отходы", "крупногабаритные отходы"),
                    ("переполненные контейнеры", "переполненные контейнеры"),
                    ("переполненные урны", "переполненные урны"),
                ],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="created_date",
            field=models.CharField(default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="application",
            name="first_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="application",
            name="last_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="application",
            name="message",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="application",
            name="patronymic",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="application",
            name="phone_number",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="application",
            name="photo_url",
            field=models.CharField(default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="application",
            name="user_id",
            field=models.CharField(default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="application",
            name="video_url",
            field=models.CharField(default="", max_length=500),
        ),
    ]
