# Generated by Django 4.1.6 on 2023-02-09 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "applications",
            "0011_alter_application_address_alter_application_app_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="event", name="description", field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="news", name="description", field=models.TextField(default=""),
        ),
    ]
