# Generated by Django 4.1.6 on 2023-02-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0012_alter_event_description_alter_news_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileStorage",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="created_at",
                        verbose_name="created_at",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="modified_at",
                        verbose_name="modified_at",
                    ),
                ),
                (
                    "id",
                    models.CharField(max_length=500, primary_key=True, serialize=False),
                ),
                (
                    "object_type",
                    models.CharField(
                        choices=[("application", "application"), ("event", "event")],
                        default="",
                        max_length=255,
                    ),
                ),
                ("object_id", models.CharField(default="", max_length=400)),
                ("file_url", models.CharField(default="", max_length=500)),
                ("created_date", models.DateField(default="", max_length=400)),
            ],
            options={"abstract": False,},
        ),
    ]
