# Generated by Django 4.1.6 on 2023-02-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0013_filestorage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="application",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="application",
            name="patronymic",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
