# Generated by Django 4.1.6 on 2023-02-09 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0014_alter_application_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="address",
            field=models.CharField(blank=True, default="", max_length=600),
        ),
        migrations.AlterField(
            model_name="application",
            name="created_date",
            field=models.CharField(blank=True, default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="application",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="application",
            name="photo_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="application",
            name="user_id",
            field=models.CharField(blank=True, default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="application",
            name="video_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="event",
            name="address",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="event",
            name="created_date",
            field=models.DateField(blank=True, default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateField(blank=True, default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="event",
            name="document_url",
            field=models.CharField(blank=True, default="", max_length=600),
        ),
        migrations.AlterField(
            model_name="event",
            name="organizer_info",
            field=models.CharField(blank=True, default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="event",
            name="time",
            field=models.CharField(blank=True, default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="event",
            name="user_id",
            field=models.CharField(blank=True, default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="filestorage",
            name="created_date",
            field=models.DateField(blank=True, default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="filestorage",
            name="file_url",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="filestorage",
            name="object_id",
            field=models.CharField(blank=True, default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="filestorage",
            name="object_type",
            field=models.CharField(
                blank=True,
                choices=[("application", "application"), ("event", "event")],
                default="",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="author_id",
            field=models.CharField(blank=True, default="", max_length=600),
        ),
        migrations.AlterField(
            model_name="news",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="news",
            name="photo_url",
            field=models.CharField(blank=True, default="", max_length=600),
        ),
        migrations.AlterField(
            model_name="news",
            name="small_description",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
