# Generated by Django 4.1.6 on 2023-02-10 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0015_alter_application_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainUser",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="created_at",
                        verbose_name="created_at",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="modified_at",
                        verbose_name="modified_at",
                    ),
                ),
                (
                    "id",
                    models.CharField(max_length=500, primary_key=True, serialize=False),
                ),
                (
                    "first_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("last_name", models.CharField(blank=True, default="", max_length=255)),
                ("username", models.CharField(blank=True, default="", max_length=255)),
                ("password", models.CharField(blank=True, default="", max_length=500)),
                ("email", models.CharField(blank=True, default="", max_length=500)),
                (
                    "phone_number",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("gender", models.CharField(blank=True, default="", max_length=500)),
                (
                    "access_type",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("avatar", models.CharField(blank=True, default="", max_length=500)),
                ("is_verified", models.BooleanField(default=False)),
            ],
            options={"abstract": False,},
        ),
    ]
