# Generated by Django 4.1.6 on 2023-02-10 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0016_mainuser"),
    ]

    operations = [
        migrations.RemoveField(model_name="application", name="user_id",),
        migrations.AddField(
            model_name="application",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="applications.mainuser",
            ),
        ),
    ]
