# Generated by Django 4.1.6 on 2023-02-10 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0017_remove_application_user_id_application_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="event", name="user_id",),
        migrations.RemoveField(model_name="news", name="author_id",),
        migrations.AddField(
            model_name="event",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="applications.mainuser",
            ),
        ),
        migrations.AddField(
            model_name="news",
            name="author",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                to="applications.mainuser",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="created_date",
            field=models.DateField(blank=True, default="", max_length=400),
        ),
        migrations.AlterField(
            model_name="news", name="created_date", field=models.DateField(),
        ),
        migrations.CreateModel(
            name="UserEvents",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="created_at",
                        verbose_name="created_at",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="modified_at",
                        verbose_name="modified_at",
                    ),
                ),
                (
                    "id",
                    models.CharField(max_length=500, primary_key=True, serialize=False),
                ),
                ("created_date", models.DateField()),
                (
                    "event",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.event",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.mainuser",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Comments",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="created_at",
                        verbose_name="created_at",
                    ),
                ),
                (
                    "modified_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="modified_at",
                        verbose_name="modified_at",
                    ),
                ),
                (
                    "id",
                    models.CharField(max_length=500, primary_key=True, serialize=False),
                ),
                ("message", models.TextField()),
                ("obj_id", models.CharField(blank=True, default="", max_length=500)),
                (
                    "object_type",
                    models.CharField(
                        blank=True,
                        choices=[("application", "application"), ("event", "event")],
                        default="",
                        max_length=255,
                    ),
                ),
                ("created_date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="applications.mainuser",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
