# Generated by Django 4.1.6 on 2023-02-10 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0020_rename_object_type_comments_obj_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="full_name",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AlterField(
            model_name="feedback", name="message", field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="phone_number",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
    ]
