# Generated by Django 4.1.6 on 2023-02-13 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "applications",
            "0021_alter_feedback_full_name_alter_feedback_message_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="message",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
