# Generated by Django 4.1.6 on 2023-02-13 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0022_alter_application_message"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="message",
            field=models.TextField(blank=True, default=""),
        ),
    ]
