# Generated by Django 4.1.6 on 2023-02-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("applications", "0023_alter_application_message"),
    ]

    operations = [
        migrations.RemoveField(model_name="userevents", name="event",),
        migrations.AddField(
            model_name="userevents",
            name="obj_id",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="userevents",
            name="obj_type",
            field=models.CharField(
                blank=True,
                choices=[("application", "application"), ("event", "event")],
                default="",
                max_length=255,
            ),
        ),
    ]
